//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscusFish.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;

    public partial class Discus
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please enter the name of strain of Discus")]
        [StringLength(100, MinimumLength = 1)]
        public string name { get; set; }

        [Required(ErrorMessage = "Please select a picture the picture of the Discus")]
        [StringLength(100, MinimumLength = 1)]
        public string image { get; set; }

        [Required(ErrorMessage = "Please enter the name of video(Note: needs to be in correct format)")]
        [StringLength(100, MinimumLength = 1)]
        public string video { get; set; }

        public HttpPostedFileBase ImageFile { get; set; }
    }
}
